Play travis
Otus-DevOps-2022-02/Yerlan-ops_infra pull request #2
Opened 2022-05-11 19:16 UTC by Yerlan-ops

1. adding workflow folder
2. Adding auto-assign.yml into .github folder
3. Adding auto-assign.yml into .github/workflow subfolder
4. Adding run-tests.yml into .github/workflow subfolder

2022-05-12 08:58 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно внести некоторые правки
Директория с пайплайнами должна называться workflows
Вы пропустили букву S в названии
Нужно поправить =)

2022-05-12 10:47 UTC, Yerlan-ops commented
Пропущенное действие наверстано: создана в корне репозитория папка play-travis и файл test.py. 
workflows название папки исправлено.

2022-05-14 09:29 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто
Апрув ^_^

2022-05-15 17:27 UTC, merged

2022-05-15 17:27 UTC, Yerlan-ops commented
thank you skeeper