YC cloud-testapp 6
Otus-DevOps-2022-02/Yerlan-ops_infra pull request #4
Opened 2022-06-20 06:51 UTC by Yerlan-ops

# Выполнено ДЗ №6

 - [x] Основное ДЗ - создание основного сервера командами вручную
 - [x] Задание дополнительное - создание второго сервера с помощью автоматического скрипта

## В процессе сделано:
 - Пункт 1 (дополнительный). Предварительные шаги. 
 Была произведена предварительная установка следующих пакетов: а) curl для тестирования подключения к удаленному серверу, и б) правка конфигурационного файла C:/Program Files/Git/etc/bash.bashrc, начиная с линии №23 следующими строками:

```
    if [ -z "$SSH_AUTH_SOCK" ] ; then
        eval `ssh-agent -s`
        ssh-add ~/.ssh/appuser
    fi
```

 - Пункт 2 (Основной). Создан скрипт startupserver.sh с заранее заданным именем хоста reddit-app2:

```
	#!bin/bash

	yc compute instance create \
	  --name reddit-app2 \
	  --hostname reddit-app2 \
	  --memory=4 \
	  --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-1604-lts,size=10GB \
	  --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 \
	  --metadata serial-port-enable=1 \
	  --zone ru-central1-a \
	  --metadata-from-file user-data=./metadata.yaml

	**sh connect_script.sh**

```
- Пункт 3 (Основной). Создан конфигурационный файл metadata.yaml, вызываемый скриптом из Пункта 2, с добавлением недостающего в образце ДЗ параметра определения сетевой зоны, т.е. серверного сайта (площадки):
```
	#cloud-config
	disable_root: true
	timezone: Asia/Almaty
	repo_update: true
	repo_upgrade: true
	apt:
	  preserve_sources_list: true

	users:
	  - name: yc-user
		groups: sudo
		shell: /bin/bash
		sudo: ['ALL=(ALL) NOPASSWD:ALL']
		ssh-authorized-keys:
		  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqZt4YB9y66fWf956T2+7g7ZuzVf/nSxa7pieoTMDOPt+MraABHNQwPPPqPGI+8uX6p0tLIEB+2Rq4vQNkpJx4m2gl/F+EfF+lM5rgCrQjFT9RsxhZqY7Jx5ECqHn356ASc19sdy0mNODaOcpefavB+JtynQQORZPTSEYCi97VgX2kBjVQZ6XrUc4jXwKJzWrcD2HJpygRiYzApWrsRCzoiBVbcNWGfbUZ8nEyQEvO45GaP71jqBmTfbGnoomsaJ8vqOJDgaTojDA/Z4GEJvNRp3CaldyVRPlMNUQSEI+BZAu5uxr0ZJFRpIVWFQqIe7MjXZPHz3wDYJJ8YcYrxtl9 appuser

	runcmd:
	 - cd ~
	 - wget https://raw.githubusercontent.com/Otus-DevOps-2022-02/Yerlan-ops_infra/cloud-testapp/install_mongodb.sh
	 - wget https://raw.githubusercontent.com/Otus-DevOps-2022-02/Yerlan-ops_infra/cloud-testapp/install_ruby.sh
	 - wget https://raw.githubusercontent.com/Otus-DevOps-2022-02/Yerlan-ops_infra/cloud-testapp/deploy.sh
	 - sudo chmod +x install_ruby.sh
	 - sudo chmod +x install_mongodb.sh
	 - sudo chmod +x deploy.sh
	 - sh install_ruby.sh
	 - sh install_mongodb.sh
	 - sh deploy.sh
```
- Пункт 4 (дополнительный). Дополнительно написан скрипт connect_script.sh (выделенный полужирным шрифтом в листинге кода Пункта 2, позволяющий автоматически определить ip-address вновь установленного сервера с заранее заданным именем хоста и номер порта приложения, с занесением в две локальные переменные соответственно. Затем подключение тестируется скриптом при помощи следующей конструкции: 
  `curl yc-user@$ipaddress:$portnumber`
Файл приложен. 

## Как запустить проект:
 - Команды указаны выше, в пп.2-4

## Как проверить работоспособность:
 - Основного сервера - по ссылке http://51.250.82.178:9292
 - Вторичного сервера - по ссылке http://51.250.64.58:9292

## PR checklist
 - [х] Выставил label с номером домашнего задания
 - [х] Выставил label с темой домашнего задания

2022-06-21 09:34 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Кажется что-то пошло не так со скриптом установки
Нужно проверить =)

2022-06-25 09:17 UTC, mrgreyves approved these changes
Здравствуйте!)
Такие приколы с монгой бывают, в этом нет ничего страшного
Перед мержем рекомендую проверить работает ли у вас приложение, можно ли добавить или посмотреть какой нибудь пост =)

2022-06-29 19:51 UTC, Yerlan-ops commented
[v](http://51.250.80.160:9292/) показывает какую-то ерунду(!)

2022-06-30 20:33 UTC, mrgreyves commented
Вывод основной страницы связан с версией ruby
Приложение не очень новое и нормально оно работает под ruby 2.4 который как раз есть в 16 04 ubuntu
Монга 3 или 4 версии так есть в репозиториях

2022-07-05 19:41 UTC, mrgreyves commented
Ерлан, здравствуйте!
Кажется что мы с вами уже разобрались с этим и оно принято
Предлагаю вам двигаться дальше в рамках выполнения следующих домашних заданий

2022-08-14 14:18 UTC, Yerlan-ops commented
Последние изменения, прошу принять. Полностью проверенные скрипты на работоспособность

2022-08-17 15:27 UTC, merged